name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '.github/workflows/test.yml'
    branches:
      - main
      - dev
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
            
      - name: Checkout `worlds`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/worlds
          token: ${{ secrets.PAT }}
          path: worlds
      
      - name: Checkout `types`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/types
          token: ${{ secrets.PAT }}
          path: types
      
      - name: Checkout `transforms`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/transforms
          token: ${{ secrets.PAT }}
          path: transforms
      
      - name: Checkout `text-rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/text-rendering
          token: ${{ secrets.PAT }}
          path: text-rendering
      
      - name: Checkout `rendering`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/rendering
          token: ${{ secrets.PAT }}
          path: rendering
      
      - name: Checkout `meshes-9s`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/meshes-9s
          token: ${{ secrets.PAT }}
          path: meshes-9s
      
      - name: Checkout `materials`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/materials
          token: ${{ secrets.PAT }}
          path: materials
      
      - name: Checkout `default-presentation-assets`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/default-presentation-assets
          token: ${{ secrets.PAT }}
          path: default-presentation-assets
      
      - name: Checkout `cameras`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/cameras
          token: ${{ secrets.PAT }}
          path: cameras
      
      - name: Checkout `automations`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/automations
          token: ${{ secrets.PAT }}
          path: automations
      
      - name: Checkout `unmanaged`
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
            
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Debug --logger "trx"
            
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          working-directory: ${{ github.event.repository.name }}
          name: Report
          path: 'tests/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: false